### ISSUE TITLE
Failed to upload sequence, again!

### ISSUE THREAD

**Issue by brmonaghan** [kartaview/upload-scripts#124]
It looks like the dreaded failed to upload sequence is back again.
Starting to upload 3 sequences...
Logged in user: snowcool776. To log out delete C:\Users\cgeek\Downloads\cg\upload-scripts-master/credentials.json
  0%|                                                                                          | 0/271 [00:00<?, ?it/s]    Failed to upload sequence at OSV\SEQ_42e50d14-ba70-4cba-903d-d277f2d61570. Restart the script in order to finish you upload for this sequence.
    Failed to upload sequence at OSV\SEQ_483f8bc9-67d7-4db3-b777-9f6f1eb3d54a. Restart the script in order to finish you upload for this sequence.
    Failed to upload sequence at OSV\SEQ_a1287087-05f6-419e-9927-7020ab7f50f4. Restart the script in order to finish you upload for this sequence.
Finished uploading
  0%|
Is anybody aware of this? @salabogdan

**Comment by robhubi** [comment]
The same here.
Last successful upload: 3 March 2022. Today's upload failed. Then updated upload scripts and recreated virtual environment. Upload still fails. Message:
`Failed to upload sequence at T:\Robert\Pictures\OSC\Seq00. Restart the script in order to finish you upload for this sequence.`
"Restart" does not lead to any other result. The folders of the sequences remain unchanged, the error message comes immediately after start. 

My system: Win 10 Pro 64 Bit, Python v 3.9.5

**Comment by brmonaghan** [comment]
So it looks like we have a MAJOR issue with Kartaview right now? @zhaitianduo

**Comment by brmonaghan** [comment]
I thought the windstorm we are having right now is causing this to occur. But now it seems to be an outage. 😠

**Comment by brmonaghan** [comment]
Works now!
Closing

**Comment by zhaitianduo** [comment]
Sorry we released a defect yesterday and fixed it after some time, sorry for the inconvenience!

**Comment by lklepner** [comment]
Ahh this likely explains why my iOS app uploads were stuck.
